# Generated by Django 5.0.3 on 2024-04-01 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('position', models.TextField(max_length=200)),
                ('type', models.TextField(max_length=50)),
                ('location', models.TextField(max_length=50)),
                ('salary', models.IntegerField()),
                ('about', models.TextField()),
                ('requirments', models.TextField()),
                ('responsibilities', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
