# Generated by Django 5.0.3 on 2024-04-01 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_career'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='career',
            name='requirments',
        ),
        migrations.RemoveField(
            model_name='career',
            name='responsibilities',
        ),
    ]
