# Generated by Django 5.0.3 on 2024-04-02 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_career_requirments_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_full_course', models.BooleanField(default=True)),
                ('is_mini_course', models.BooleanField(default=True)),
                ('is_popular', models.BooleanField(default=True)),
                ('is_tutoring', models.BooleanField(default=True)),
                ('title', models.TextField(max_length=50)),
                ('price', models.IntegerField()),
                ('units', models.IntegerField()),
                ('is_on_sale', models.BooleanField(default=True)),
                ('receipt_description', models.TextField(max_length=50)),
                ('percent', models.IntegerField()),
                ('has_checkout', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField()),
                ('image', models.TextField()),
            ],
        ),
    ]
