# Generated by Django 5.0.3 on 2024-04-02 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_coursecard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('first_name', models.TextField(max_length=50)),
                ('last_name', models.TextField(max_length=50)),
                ('photo', models.TextField(max_length=200)),
                ('position', models.TextField(max_length=100)),
                ('location', models.TextField(max_length=100)),
                ('about', models.TextField()),
                ('is_mentor', models.BooleanField(default=False)),
                ('is_tutor', models.BooleanField(default=False)),
                ('is_instructor', models.BooleanField(default=False)),
                ('is_TA', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
