# Generated by Django 4.2.6 on 2024-04-07 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_honeycombs_delete_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='honeycombs',
            name='link',
            field=models.TextField(),
        ),
    ]
